---
- name: install packages for cinnamon desktop
  package:
    name: "{{ package }}"
    state: present
  loop:
    - cinnamon
    - dbus-x11
    - "{{ gpu_graphics_driver_package }}"
  loop_control:
    loop_var: package
